services:
  nyomda:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/nyomda:latest
    container_name: nyomda
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
